---
# tasks file for ntp
- name: install packages
  dnf:
    name: "{{ packages }}"
    state: latest

- name: Add line to chrony config to allow local subnet to access service
  lineinfile:
    path: /etc/chrony.conf
    regexp: '^allow'
    line: "allow {{ net_mask | ipaddr('net') }}"

- name: setup firewall
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
    zone: public
  with_items: "{{ services }}"
  notify: restart chrony
