

- name: Create a directory for OCP install
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ folders }}"

#- name: Download files for install
#  get_url:
#    url: "{{ item }}"
#    dest: "{{ ocp_folder }}/"
#  loop:
#    - "{{ ocp_image_url }}{{ ocp_image }}"
#
- name: Unarchive files to install directory
  unarchive:
    src: "{{ item }}"
    dest: /root/bin/
    remote_src: yes
  loop:
    - "{{ ocp_installer_url }}{{ ocp_installer }}"
    - "{{ ocp_client_url }}{{ ocp_client }}"

- name: Generate SSH keys on Bastion
  openssh_keypair:
    path: /root/.ssh/id_rsa
    force: yes
  register: sshkey

- name: Template a ignition file to bastion install folder
  template:
    src: install-config.yaml.j2
    dest: /root/install-config.yaml

- name: Create ignition files
  command: openshift-install create ignition-configs
    --dir={{ ign_folder }}
