---
- name: install packages
  dnf:
    name: "{{ packages }}"
    state: latest

- name: setup firewall
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
    zone: public
  with_items: "{{ services }}"
  notify: restart firewalld

- name: setup firewall rules - ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
    zone: public
  with_items: "{{ ports }}"
  notify: restart firewalld

#https://github.com/linux-system-roles/selinux/blob/master/selinux-playbook.yml
- name: execute the role and catch errors
  block:
    - include_role:
        name: linux-system-roles.selinux
  rescue:
    # Fail if failed for a different reason than selinux_reboot_required.
    - name: handle errors
      fail:
        msg: "selinx port role failed"
      when: not selinux_reboot_required

    - name: restart managed host
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      async: 1
      poll: 0
      ignore_errors: true

    - name: wait for managed host to come back
      wait_for_connection:
        delay: 10
        timeout: 300

    - name: reapply the role
      include_role:
        name: linux-system-roles.selinux

- name: copy over haproxy configuration
  template:
    src: haproxy.conf.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: haproxy
    group: haproxy

- name: Force restart of haproxy
  service:
    name: haproxy
    state: restarted
