---
# tasks file for createVMs
- name: Setup OCP bootstrap VM
  command: "virt-install
    --name {{ hostvars[item]['inventory_hostname'] }}
    --disk size=50
    --ram 16000
    --cpu host
    --vcpus 4
    --os-type linux
    --os-variant rhel7
    --network network={{ bridge }},mac={{ hostvars[item]['ethernet'] }}
    --noautoconsole
    --location http://{{ hostvars['bastion']['inventory_hostname'] }}:8080/ignition/
    --extra-args 'nomodeset rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=vda coreos.inst.image_url=http://{{ hostvars['bastion']['inventory_hostname'] }}:8080/ignition/{{ ocp_image }} coreos.inst.ignition_url=http://{{ hostvars['bastion']['inventory_hostname'] }}:8080/ignition/{{ hostvars[item]['ign_name'] }}.ign'"
  loop: "{{ groups['ocp'] }}"
