---
# tasks file for redfish
- name: Power Off
  redfish_command:
    category: Systems
    command: PowerForceOff
    baseuri: "{{ hostvars[item]['baseuri'] }}"
    username: "{{ lookup('vars', 'vault_' + item + '_user') }}"
    password: "{{ lookup('vars', 'vault_' + item + '_pass') }}"
  register: bios_attribute
  loop: "{{ groups['kvm'] }}"
  when: hostvars[item]['redfish'] == 'true'

- name: Set server to PXE boot
  redfish_command:
    category: Systems
    command: SetOneTimeBoot
    bootdevice: "Pxe"
    baseuri: "{{ hostvars[item]['baseuri'] }}"
    username: "{{ lookup('vars', 'vault_' + item + '_user') }}"
    password: "{{ lookup('vars', 'vault_' + item + '_pass') }}"
  register: bios_attribute
  loop: "{{ groups['kvm'] }}"
  when: hostvars[item]['redfish'] == 'true'

- name: Power On
  redfish_command:
    category: Systems
    command: PowerOn
    baseuri: "{{ hostvars[item]['baseuri'] }}"
    username: "{{ lookup('vars', 'vault_' + item + '_user') }}"
    password: "{{ lookup('vars', 'vault_' + item + '_pass') }}"
  register: bios_attribute
  loop: "{{ groups['kvm'] }}"
  when: hostvars[item]['redfish'] == 'true'
