---
- name: KVM Setup
  hosts: kvm01
  vars_files:
    - vault
    - play_vars.yml
    - kvm-system-roles-network.yml
  roles:
    - packages_and_bridge
# On a RHEL system this would be rhel-system-roles.networking
    - rhel-system-roles.network
    - createVMs
