---
- name: Bastion Setup plus PXE boot kvm node/s
  hosts: bastion
  vars_files:
    - play_vars.yml
    - vault
  roles:
  #  - unbound
  #  - dhcp
  #  - ntp
  #  - haproxy
  #  - httpd
    - pxe
  #  - redfish

#- name: KVM Setup
#  hosts: kvm
#  vars_files:
#    - vault
#    - play_vars.yml
#    - rhel-system-roles-networking.yml
#  roles:
#    - packages
#    - rhel-system-roles.network
#    - networking
#    - rhcos
#  when: hostvars[host]['kvm'] == 'true'
