---
- name: Bastion Setup (basically install the roles for rhel-system)
  hosts: bastion
  roles:
    - bastion_packages

- name: KVM Setup
  hosts: kvm
  vars_files:
    - vault
    - play_vars.yml
  roles:
    - packages
    - firewall
    - registry
