---
- name: Bastion Setup plus PXE boot kvm node/s
  hosts: bastions
  vars_files:
    - play_vars.yml
    - vault
  roles:
  #  - unbound
  #  - dhcp
  #  - ntp
  #  - haproxy
  #  - httpd
  #  - pxe
  #  - redfish

- name: KVM Setup
  hosts: kvm
  vars_files:
    - vault
    - play_vars.yml
    - rhel-system-roles-networking.yml
  roles:
    #- packages
    # On a RHEL system this would be rhel-system-roles.networking
    #- linux-system-roles.network

- name: Install OCP installer and client plus pull secret
  hosts: bastions
  vars_files:
    - play_vars.yml
    - vault
  roles:
    - ocp-prep
