---
- name: Bastion Setup (basically install the roles for rhel-system)
  hosts: bastion
  vars_files:
    - play_vars.yml
    - vault
  roles:
  #  - unbound
  #  - dhcp
  #  - ntp
  #  - haproxy
    - httpd
    - pxe

#- name: KVM Setup
#  hosts: kvm
#  vars_files:
#    - vault
#    - play_vars.yml
#    - rhel-system-roles-networking.yml
#    - vm_data.yml
#  roles:
#    - packages
#    - rhel-system-roles.network
#    - networking
#    - dhcp
#    - unbound
#    - ntp
#    - httpd
#    - rhcos
