---
# tasks file for upi.offline
- name: Remove old ssh keys before creating new VMs
  lineinfile:
    path: "{{ homedir }}.ssh/known_hosts"
    regexp: ".*{{ item.name }}.*"
    state: absent
  with_items:
  - "{{ named_hosts }}"

# Setup client and installer
- name: Setup directory listed in environment PATH variable
  file:
    path: "{{ homedir }}.local/bin"
    state: directory
    mode: '0755'
- name: Copy over client
  unarchive:
    src: "{{ ocp_client }}"
    dest: "{{ homedir }}.local/bin"
    remote_src: yes
    creates: "{{ homedir }}.local/bin/oc"
- name: Copy over installer
  unarchive:
    src: "{{ ocp_installer }}"
    dest: "{{ homedir }}.local/bin"
    remote_src: yes
    creates: "{{ homedir }}.local/bin/openshift-install"

# Setup working direcotry
- name: Remove old working directory
  file:
    path: "{{ homedir }}/bare-metal"
    state: absent
- name: Recreate new working duirectory for installer 
  file:
    path: "{{ homedir }}/bare-metal"
    state: directory
    mode: '0755'
- shell: echo -n 'admin:admin123' | base64 -w0
  register: nexus_digest_output
- set_fact:
    nexus_digest: "{{ nexus_digest_output.stdout }}"
- command: ssh-keygen -q -t rsa -f /root/.ssh/id_ocplabs -C "" -N ""
  args:
    creates: /root/.ssh/id_ocplabs
- shell: "cat /root/.ssh/id_ocplabs.pub | cut -d' ' -f1,2"
  register: ssh_key_output
- set_fact:
    ssh_key: "{{ ssh_key_output.stdout }}"
- shell: "openssl s_client -showcerts -servername {{ hostvars['bastion']['ansible_host'] }} -connect {{ hostvars['bastion']['ansible_host'] }}:{{ nexus_port }} </dev/null 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sed 's/\\(.*\\)/  \\1/g'"
  register: additional_trustbundle_output
- set_fact:
    additional_trustbundle: "{{ additional_trustbundle_output.stdout }}"
- template:
    src: install-config.j2
    dest: "{{ ocp4_home }}/bare-metal/install-config.yaml"
- shell: "{{ ocp4_home }}/bin/openshift-install --dir {{ ocp4_home }}/bare-metal create manifests"
- shell: "{{ ocp4_home }}/bin/openshift-install --dir {{ ocp4_home }}/bare-metal create ignition-configs"
