---
# handlers file for httpd
- name: reload systemctl
  systemd:
    daemon_reload: yes

- name: start service
  systemd:
    name: "{{ service_name }}"
    state: started

- name: restart service
  systemd:
    name: "{{ service_name }}"
    state: restarted
