---
# tasks file for dhcp
- name: Install dhcp service plus dependencies
  dnf:
    name: "{{ packages }}"
    state: latest

- name: setup firewall
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
    zone: public
  with_items: "{{ services }}"

- name: Copy over configuration
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
  notify: restart dhcpd
