---
# tasks file for httpd
- name: Login to registry as podman_image seems to not do this properly
  command: podman login
    --username "{{ rhn_username }}"
    --password "{{ rhn_password }}"
    registry.redhat.io

- name: Download httpd image
  podman_image:
    name: registry.redhat.io/rhel8/httpd-24

- name: Create folder for httpd
  file:
    path: /opt/registry/www/html
    state: directory
    mode: '0775'

- name: setup firewall rules - services
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
    zone: public
  with_items: "{{ services }}"

- name: setup firewall rules - ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
    zone: public
  with_items: "{{ ports }}"

- name: "create systemd service file for container: {{ container_name }}"
  template:
    src: systemd-service-single.j2
    dest: "{{ service_files_dir }}/{{ service_name }}"
    owner: root
    group: root
    mode: 0644
  notify: reload systemctl

- name: ensure "{{ service_name }}" is enabled at boot, and systemd reloaded
  systemd:
    name: "{{ service_name }}"
    enabled: yes
    daemon_reload: yes

- name: ensure "{{ service_name }}" is running
  service:
    name: "{{ service_name }}"
    state: started
