---
# tasks file for httpd
- name: Login to registry as podman_image seems to not do this properly
  command: podman login
    --username "{{ rhn_username }}"
    --password "{{ rhn_password }}"
    registry.redhat.io

- name: Download httpd image
  podman_image:
    name: registry.redhat.io/rhel8/httpd-24

- name: Create folder for httpd
  file:
    path: /opt/registry/www/html
    state: directory
    mode: '0775'

- name: setup firewall rules - services
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
    zone: public
  with_items: "{{ services }}"

- name: setup firewall rules - ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
    zone: public
  with_items: "{{ ports }}"

- name: Dangerous for multi use envirnment
  command: podman stop --all

- name: Remove all containers
  command: podman rm --all --force

- name: Build and run httpd
  command: podman run
    --detach
    --restart always
    --name httpd
    --publish 8080:8080
    --volume /opt/registry/www:/var/www:z
    rhel8/httpd-24
