---
# tasks file for ocp-prep
# go here to get your long lived access toekn https://cloud.redhat.com/openshift/token
- name: Generate access token with offline token
  uri:
    url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    method: POST
    body_format: form-urlencoded
    body:
    - [ grant_type, refresh_token ]
    - [ client_id, cloud-services ]
    - [ refresh_token, "{{ vault_token_long }}" ]
  register: access_tokens

- name: Generate pull secret from access_token
  uri:
    url: https://api.openshift.com/api/accounts_mgmt/v1/access_token
    method: POST
    headers:
      Content-Type: application/json
      Authorization: Bearer {{ access_tokens.json.access_token }}
  register: pull_secret

- debug:
    msg: {{ json.dumps(pull_secret.json)
